package yandex.yandex_7_training.yandex_7_training_4_dz

fun main(){
    val input = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n" +
            "XXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX\n" +
            "XXXXX XXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXX\n" +
            "XXXX XXXXX XXXXX XXXXXx XXX XXXXXXx XXX XXXXXX XXXXXXXXXXXX\n" +
            "XXXX XXXXXXX XXXXX XXXXXXX XXX XXXXXXX XXX XXXXXXXX XXXXXXXXXXXX\n" +
            "XXXXX XXXXXXX XXXXX XXXXXXX XXX XXXXXXXX XXX XXXXXXXX XXXXXXXXXXXX\n" +
            "XXXXXXx XXXXX XXXXXX XXXXXXX XXX XXXXXXXX XXX XXXXXXX xXXXXXXXXXXXXX\n" +
            "XXXXXXXXXXXX XXXXXXX XXXXXXXX XXX XXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX\n" +
            "XXXXXXXXXXX XXXXXXXX XXXXXXXX XXX XXXXXXXX XXX XXX XXXXXXXXXXXXXXX\n" +
            "XXXXXXXX XXXXXXXXX XXXXXXXX XXX XXXXXXXXX XXX X XXXXXXXXXXXXX\n" +
            "XXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXX XXX XXX XXXXXXXXXXXX\n" +
            "XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXX XXXXXX XXXXXXXXXXXX\n" +
            "XXXXX XXXXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXX\n" +
            "XXXXX XXXXXXXXXXXXX XXXXXX xXXXXX XXXXXX xXXXX XXXXXX XXXXXXXXXXXX\n" +
            "XXXXX X xXXXXXXX XXX XXXXXXX XX XXXXXX XXX XXXXXXXXXXXXX\n" +
            "XXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX\n" +
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n" +
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 2006 Russia Team Programming Contest XX\n"

    val ans = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n" +
            "XXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX\n" +
            "XXXXX XXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXX\n" +
            "XXXX XXXXX XXXXX XXXXXx XXX XXXXXXx XXX XXXXXX XXXXXXXXXXXX\n" +
            "XXXX XXXXXXX XXXXX XXXXXXX XXX XXXXXXX XXX XXXXXXXX XXXXXXXXXXXX\n" +
            "XXXXX XXXXXXX XXXXX XXXXXXX XXX XXXXXXXX XXX XXXXXXXX XXXXXXXXXXXX\n" +
            "XXXXXXx XXXXX XXXXXX XXXXXXX XXX XXXXXXXX XXX XXXXXXX xXXXXXXXXXXXXX\n" +
            "XXXXXXXXXXXX XXXXXXX XXXXXXXX XXX XXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX\n" +
            "XXXXXXXXXXX XXXXXXXX XXXXXXXX XXX XXXXXXXX XXX XXX XXXXXXXXXXXXXXX\n" +
            "XXXXXXXX XXXXXXXXX XXXXXXXX XXX XXXXXXXXX XXX X XXXXXXXXXXXXX\n" +
            "XXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXX XXX XXX XXXXXXXXXXXX\n" +
            "XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXX XXXXXX XXXXXXXXXXXX\n" +
            "XXXXX XXXXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXX\n" +
            "XXXXX XXXXXXXXXXXXX XXXXXX xXXXXX XXXXXX xXXXX XXXXXX XXXXXXXXXXXX\n" +
            "XXXXX X xXXXXXXX XXX XXXXXXX XX XXXXXX XXX XXXXXXXXXXXXX\n" +
            "XXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX\n" +
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n" +
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 2006 Russia Team Programming Contest XX"

    val verdict = ans.trim() == input.trim()
    println(verdict)
}